//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Comanda = new HashSet<Comanda>();
        }
    
        public int Id { get; set; }
        public string Dni { get; set; }
        public string Nom { get; set; }
        public string Cognom { get; set; }
        public Nullable<int> Edat { get; set; }
        public string ImageClient { get; set; }
        public Nullable<System.DateTime> DataProperaVisita { get; set; }
        public int ComercialId { get; set; }
    
        public virtual Comercial Comercial { get; set; }
        public virtual ICollection<Comanda> Comanda { get; set; }
        public virtual Localitzacio Localitzacio { get; set; }
    }
}
