//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comanda
    {
        public Comanda()
        {
            this.Comanda_Producte = new HashSet<Comanda_Producte>();
        }
    
        public int Id { get; set; }
        public bool Lliurada { get; set; }
        public System.DateTime Data { get; set; }
        public int ClientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Comanda_Producte> Comanda_Producte { get; set; }
    }
}
