//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localitzacio
    {
        public int Id { get; set; }
        public string CodiPostal { get; set; }
        public string Direccio { get; set; }
        public string Poblacio { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public int ClientId { get; set; }
        public int ComercialId { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
