//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class m13_projectEntities1 : DbContext
    {
        public m13_projectEntities1()
            : base("name=m13_projectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<CategoriaLog> CategoriaLog { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Comanda> Comanda { get; set; }
        public virtual DbSet<Comanda_Producte> Comanda_Producte { get; set; }
        public virtual DbSet<Comercial> Comercial { get; set; }
        public virtual DbSet<Localitzacio> Localitzacio { get; set; }
        public virtual DbSet<Producte> Producte { get; set; }
        public virtual DbSet<ProducteLog> ProducteLog { get; set; }
        public virtual DbSet<Usuari> Usuari { get; set; }
    }
}
