//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuari
    {
        public int Id { get; set; }
        public string Dni { get; set; }
        public string Nom { get; set; }
        public string Cognom { get; set; }
        public string Usuari1 { get; set; }
        public string Contrasenya { get; set; }
        public string Imatge { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Comercial Comercial { get; set; }
    }
}
